# Generated by Django 4.1.5 on 2023-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='destination_photos'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_photos'),
        ),
    ]
