# Generated by Django 4.1.5 on 2023-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_hotel_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
