# Generated by Django 4.1.5 on 2023-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_destination_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='visiting_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
