# Generated by Django 4.1.5 on 2023-01-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_destination_visiting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='visiting_time',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
